services:
  postgres:
    image: postgres
    container_name: posgtres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ayoub
      POSTGRES_PASSWORD: ayoub
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ayoub@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: ayoub
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data

volumes:
  local_pgdata:
  pgadmin-data: