server:
  port: 8080

spring:
  application:
    name: projet
  datasource:
    username: ayoub
    url: jdbc:postgresql://localhost:5432/ayoub
    password: ayoub
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
#eureka:
#  client:
#   service-url:
#     defaultzone: http://localhost:8761/eureka
#   fetch-registry: true
#   registry-with-eureka: true